# Generated by Django 4.2.2 on 2023-06-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
