# Generated by Django 4.2.2 on 2023-06-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0004_alter_customuser_managers_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='利用中'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='ユーザー名'),
        ),
    ]
