# Generated by Django 4.2.2 on 2023-06-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0005_alter_customuser_email_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='退職者等、利用しないユーザーは削除せずにこのチェックを外してください。', verbose_name='利用中'),
        ),
    ]
