# Generated by Django 4.2.2 on 2023-06-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0007_alter_bookmark_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'ブックマーク', 'verbose_name_plural': '7.ブックマーク'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': '4.カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': '6.ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部署', 'verbose_name_plural': '5.部署'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'マニュアル', 'verbose_name_plural': '3.マニュアル'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order'], 'verbose_name': '作業手順', 'verbose_name_plural': '2.作業手順'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '作業', 'verbose_name_plural': '1.作業'},
        ),
    ]
