# Generated by Django 4.2.2 on 2023-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0010_alter_bookmark_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ステップ'),
        ),
    ]
