# Generated by Django 4.2.2 on 2023-06-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manualapp', '0012_bookmark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manualapp.department', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ドキュメントファイル名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manualapp.category', verbose_name='カテゴリ'),
        ),
    ]
